"""add fields to users table

Revision ID: 6a06a4d896f4
Revises: fe20917a8e12
Create Date: 2020-12-15 18:51:43.208339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a06a4d896f4'
down_revision = 'fe20917a8e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('job_title', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'job_title')
    # ### end Alembic commands ###
